In [7]:
import pandas as pd
 
a=pd.DataFrame({"x":[10,20,None]}) 


print(a)


a.fillna(value=9, inplace=True)
a

      x
0  10.0
1  20.0
2   NaN

      x
0  10.0
1  20.0
2   9.0

In [3]:
a=pd.DataFrame({"x":[10,20,None]}) 
a.dropna( inplace=True)   #drop the nan
a

      x
0  10.0
1  20.0

In [17]:
info = pd.DataFrame([[1,5,7],[10,12,15],[18,21,24]],columns=['X','Y','Z'])

info.agg(['sum','min','max'])

      X   Y   Z
sum  29  38  46
min   1   5   7
max  18  21  24

In [ ]:
import pandas as pd
import numpy as np

info = pd.DataFrame([[2, 7]] * 4, columns=['P', 'Q'])

print(info)

print(info.apply(np.sqrt))

print()

print(info.apply(np.sum, axis=0))

print()

print(info.apply(np.sum, axis=1))

print()

print(info)

   P  Q
0  2  7
1  2  7
2  2  7
3  2  7
          P         Q
0  1.414214  2.645751
1  1.414214  2.645751
2  1.414214  2.645751
3  1.414214  2.645751

P     8
Q    28
dtype: int64

0    9
1    9
2    9
3    9
dtype: int64

   P  Q
0  2  7
1  2  7
2  2  7
3  2  7

In [ ]:
import pandas as pd

a = {'col1': [1, 2], 'col2': [3, 4]}

info = pd.DataFrame(a)

print(info.dtypes)

col1    int64
col2    int64
dtype: object

In [ ]:
import pandas as pd

a = {'col1': [1, 2], 'col2': [3, 4]}

info = pd.DataFrame(data=a)

print(info.dtypes)

print()


print(info.astype('int32').dtypes)

print()


print(info.astype({'col1': 'int32'}).dtypes)

col1    int64
col2    int64
dtype: object

col1    int32
col2    int32
dtype: object

col1    int32
col2    int64
dtype: object

In [21]:
import pandas as pd
import numpy as np

info = pd.DataFrame({
    "Person": ["Parker", "Smith", "William", "John"],
    "Age": [27, 29, np.nan, 32]
})

print(info.count())

Person    4
Age       3
dtype: int64

In [20]:
import pandas as pd
import numpy as np

info = pd.DataFrame({
    "Person": ["Parker", "Smith", "William", "John"],
    "Age": [27, 29, 26, 32]
})

print(info.count(axis='columns'))

0    2
1    2
2    2
3    2
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

info = pd.DataFrame({'num': np.random.randint(1, 10, 7)})    #index 7 and  btw 1 to 9

print(info)

print()

info = pd.cut(info['num'],bins=[1, 5, 10],labels=['Lows', 'Highs'],right=False)

print(info)





print(info.unique())

   num
0    1
1   10
2    7

0     Lows
1      NaN
2    Highs
Name: num, dtype: category
Categories (2, object): ['Lows' < 'Highs']
['Lows', NaN, 'Highs']
Categories (2, object): ['Lows' < 'Highs']

In [ ]:
import pandas as pd
import numpy as np

info = pd.DataFrame({'num': np.random.randint(1, 10, 7)})

print(info)

info['numlab'] = pd.cut(x=info['num'] ,bins=[1, 7, 10],labels=['Lows', 'Highs'],right=False)

print(info)

print(info['numlab'].unique())

   num
0    4
1    4
2    2
3    1
4    1
5    5
6    6
   num numlab
0    4   Lows
1    4   Lows
2    2   Lows
3    1   Lows
4    1   Lows
5    5   Lows
6    6   Lows
['Lows']
Categories (2, object): ['Lows' < 'Highs']